window.SITE_DATA = {
  about: {
    title: 'О проекте «Таулу Алимле»',
    text: 'Сайт объединяет информацию о докторах и кандидатах наук, новостях, мероприятиях и научных публикациях. Архитектура построена как каталог с поиском, фильтрацией и отдельными страницами людей. Библиотека автоматически собирает публикации, привязанные к карточкам авторов.',
    goals: [
      'Систематизация информации о научном сообществе.',
      'Публикация и распространение научных трудов в формате PDF.',
      'Создание единой библиотеки по отраслям науки и авторам.',
      'Приём заявок на регистрацию с ручной модерацией администратора.'
    ]
  },
  scienceBranches: [
    'Биология', 'История', 'Математика', 'Медицина', 'Технические науки',
    'Физика', 'Филология', 'Химия', 'Экономика', 'Юриспруденция', 'Общественные науки'
  ],
  doctors: [
    {
      id: 'd1', firstName: 'Аминат', lastName: 'Бекмурзова', middleName: 'Хасанбиевна', maidenName: 'Токова',
      degree: 'Доктор филологических наук', branch: 'Филология', birth: '14 мая 1972, Нальчик',
      education: 'КБГУ, филологический факультет, 1994. Специальность: филология. Квалификация: филолог, преподаватель.',
      postgraduate: 'Докторантура Института языкознания РАН, 2006.',
      titleInfo: 'Доктор филологических наук, профессор. Учёная степень присвоена в 2008 году.',
      thesis: 'Языковые процессы в карачаево-балкарской научной и публицистической традиции.',
      work: 'Профессор кафедры филологии и межкультурной коммуникации.',
      publications: ['История письменной традиции Карачая и Балкарии','Терминология гуманитарных наук на тюркской основе'],
      photoInitials: 'АБ', files: ['f1','f2']
    },
    {
      id: 'd2', firstName: 'Марат', lastName: 'Кучуков', middleName: 'Азретович', maidenName: '',
      degree: 'Доктор технических наук', branch: 'Технические науки', birth: '3 февраля 1968, Чегем',
      education: 'МГТУ им. Н. Э. Баумана, 1991. Специальность: машиностроение.',
      postgraduate: 'Докторантура СПбПУ, 2004.',
      titleInfo: 'Доктор технических наук, профессор. Учёная степень присвоена в 2007 году.',
      thesis: 'Интеллектуальные системы управления высоконагруженными производственными комплексами.',
      work: 'Заведующий лабораторией цифровых производственных систем.',
      publications: ['Надёжность производственных линий в условиях многопараметрической нагрузки'],
      photoInitials: 'МК', files: ['f3']
    },
    {
      id: 'd3', firstName: 'Зарема', lastName: 'Боташева', middleName: 'Магометовна', maidenName: '',
      degree: 'Доктор экономических наук', branch: 'Экономика', birth: '9 сентября 1977, Карачаевск',
      education: 'Финансовый университет, 1999. Специальность: экономика.',
      postgraduate: 'Аспирантура и докторантура РЭУ им. Плеханова.',
      titleInfo: 'Доктор экономических наук, профессор.',
      thesis: 'Развитие региональных моделей научно-образовательной экономики.',
      work: 'Профессор кафедры региональной экономики.',
      publications: ['Экономика знаний в горных регионах','Сценарии развития научных экосистем'],
      photoInitials: 'ЗБ', files: ['f4']
    }
  ],
  candidates: [
  {
    "id": "cb1",
    "firstName": "Халимат",
    "lastName": "Абаева",
    "middleName": "Алиевна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АХ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb2",
    "firstName": "Залимхан",
    "lastName": "Абдуллаев",
    "middleName": "Мухадинович",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЗ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb3",
    "firstName": "Камиль",
    "lastName": "Азаматов",
    "middleName": "Гитчеевич",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АК",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb4",
    "firstName": "Мухарбек",
    "lastName": "Азаматов",
    "middleName": "Азаматович",
    "maidenName": "",
    "degree": "Кандидат сельскохозяйственных наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат сельскохозяйственных наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb5",
    "firstName": "Альбина",
    "lastName": "Азаматова",
    "middleName": "Бекировна",
    "maidenName": "",
    "degree": "Кандидат биологических наук",
    "branch": "Биология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат биологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb6",
    "firstName": "Гюльджан",
    "lastName": "Азаматова",
    "middleName": "Камилевна",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АГ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb7",
    "firstName": "Нуржан",
    "lastName": "Азаматова",
    "middleName": "Салиховна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АН",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb8",
    "firstName": "Римма",
    "lastName": "Азаматова",
    "middleName": "Маликовна",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АР",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb9",
    "firstName": "Элеонора",
    "lastName": "Азаматова",
    "middleName": "Камилевна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЭ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb10",
    "firstName": "Оюс",
    "lastName": "Айшаев",
    "middleName": "Ортабаевич",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АО",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb11",
    "firstName": "Светлана",
    "lastName": "Акаева",
    "middleName": "Ахматовна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АС",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb12",
    "firstName": "Халимат",
    "lastName": "Аккаева",
    "middleName": "Алиевна",
    "maidenName": "",
    "degree": "Кандидат юридических наук",
    "branch": "Юриспруденция",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат юридических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АХ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb13",
    "firstName": "Мужигит",
    "lastName": "Аккиев",
    "middleName": "Исмаилович",
    "maidenName": "",
    "degree": "Кандидат биологических наук",
    "branch": "Биология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат биологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb14",
    "firstName": "Азамат",
    "lastName": "Аккизов",
    "middleName": "Магомедович",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb15",
    "firstName": "Азамат",
    "lastName": "Аккизов",
    "middleName": "Юсуфович",
    "maidenName": "",
    "degree": "Кандидат биологических наук",
    "branch": "Биология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат биологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb16",
    "firstName": "Шарафутдин",
    "lastName": "Аккизов",
    "middleName": "Ачеевич",
    "maidenName": "",
    "degree": "Кандидат сельскохозяйственных наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат сельскохозяйственных наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АШ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb17",
    "firstName": "Алим",
    "lastName": "Алафаев",
    "middleName": "Азретович",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb18",
    "firstName": "Мурат",
    "lastName": "Алиев",
    "middleName": "Магомедович",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb19",
    "firstName": "Амина",
    "lastName": "Алиева",
    "middleName": "Магомедовна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb20",
    "firstName": "Ирина",
    "lastName": "Алиева",
    "middleName": "Захаровна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АИ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb21",
    "firstName": "Миррат",
    "lastName": "Аликаева",
    "middleName": "Рашидовна",
    "maidenName": "Тогузаева",
    "degree": "Кандидат филологических наук",
    "branch": "Филология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат филологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb22",
    "firstName": "Лариса",
    "lastName": "Аликаева",
    "middleName": "Солтанхаметовна",
    "maidenName": "",
    "degree": "Кандидат филологических наук",
    "branch": "Филология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат филологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЛ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb23",
    "firstName": "Аслан",
    "lastName": "Анаев",
    "middleName": "Хусейнович",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb24",
    "firstName": "Марат",
    "lastName": "Анаев",
    "middleName": "Азретович",
    "maidenName": "",
    "degree": "Кандидат психологических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат психологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb25",
    "firstName": "Мухамат",
    "lastName": "Анаев",
    "middleName": "Азретович",
    "maidenName": "",
    "degree": "Кандидат географических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат географических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb26",
    "firstName": "Расул",
    "lastName": "Анаев",
    "middleName": "Балукуевич",
    "maidenName": "",
    "degree": "Кандидат технических наук",
    "branch": "Технические науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат технических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АР",
    "files": [],
    "notes": "Москва",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb27",
    "firstName": "Танзиля",
    "lastName": "Анаева",
    "middleName": "Мурадовна",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АТ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb28",
    "firstName": "Сафар",
    "lastName": "Аппаев",
    "middleName": "Пахаович",
    "maidenName": "",
    "degree": "Кандидат сельскохозяйственных наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат сельскохозяйственных наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АС",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb29",
    "firstName": "Жанна",
    "lastName": "Аппаева",
    "middleName": "Юсуповна",
    "maidenName": "",
    "degree": "Кандидат физико-математических наук",
    "branch": "Физика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат физико-математических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЖ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "cb30",
    "firstName": "Фатима",
    "lastName": "Аппаева",
    "middleName": "Касымовна",
    "maidenName": "",
    "degree": "Кандидат филологических наук",
    "branch": "Филология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат филологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АФ",
    "files": [],
    "notes": "",
    "ethnicGroup": "balqar",
    "sourceListDate": "16.12.2025"
  },
  {
    "id": "ck1",
    "firstName": "Азрет",
    "lastName": "Акбаев",
    "middleName": "Алиевич",
    "maidenName": "",
    "degree": "Кандидат юридических наук",
    "branch": "Юриспруденция",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат юридических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck2",
    "firstName": "Дианна",
    "lastName": "Акбаева",
    "middleName": "Джашарбековна",
    "maidenName": "Биджиева",
    "degree": "Кандидат психологических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат психологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АД",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck3",
    "firstName": "Фатима",
    "lastName": "Абаева",
    "middleName": "Валерьевна",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АФ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck4",
    "firstName": "Абдул-Керим",
    "lastName": "Абазалиев",
    "middleName": "Юсуфович",
    "maidenName": "",
    "degree": "Кандидат физико-математических наук",
    "branch": "Физика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат физико-математических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck5",
    "firstName": "Зарема",
    "lastName": "Абазалиева",
    "middleName": "Абдул-Керимовна",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЗ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck6",
    "firstName": "Лариса",
    "lastName": "Абазалиева",
    "middleName": "Хасанбиевна",
    "maidenName": "Боташева",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЛ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck7",
    "firstName": "Марджан",
    "lastName": "Абазалиева",
    "middleName": "Ахматовна",
    "maidenName": "",
    "degree": "Кандидат технических наук",
    "branch": "Технические науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат технических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck8",
    "firstName": "Фатима",
    "lastName": "Абазалиева",
    "middleName": "Магомедовна",
    "maidenName": "Шидакова",
    "degree": "Кандидат психологических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат психологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АФ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck9",
    "firstName": "Альберт",
    "lastName": "Абайханов",
    "middleName": "Зекерьяевич",
    "maidenName": "",
    "degree": "Кандидат ветеринарных наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат ветеринарных наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck10",
    "firstName": "Касым",
    "lastName": "Абайханов",
    "middleName": "Адурхаевич",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АК",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck11",
    "firstName": "Мусса",
    "lastName": "Абайханов",
    "middleName": "Халитович",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck12",
    "firstName": "Расул",
    "lastName": "Абайханов",
    "middleName": "Иосифович",
    "maidenName": "",
    "degree": "Кандидат медицинских наук",
    "branch": "Медицина",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат медицинских наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АР",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck13",
    "firstName": "Умар",
    "lastName": "Абайханов",
    "middleName": "Иссаевич",
    "maidenName": "",
    "degree": "Кандидат геолого-минералогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат геолого-минералогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АУ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck14",
    "firstName": "Амина",
    "lastName": "Абайханова",
    "middleName": "Асланбековна",
    "maidenName": "",
    "degree": "Кандидат географических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат географических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck15",
    "firstName": "Лаура",
    "lastName": "Абайханова",
    "middleName": "Казимовна",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЛ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck16",
    "firstName": "Патия",
    "lastName": "Абайханова",
    "middleName": "Исмаиловна",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АП",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck17",
    "firstName": "Лаура",
    "lastName": "Абрекова",
    "middleName": "Казбековна",
    "maidenName": "",
    "degree": "Кандидат биологических наук",
    "branch": "Биология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат биологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЛ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck18",
    "firstName": "Мухаммат",
    "lastName": "Аджиев",
    "middleName": "Срафилович",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck19",
    "firstName": "Руслан",
    "lastName": "Аджиев",
    "middleName": "Казбекович",
    "maidenName": "",
    "degree": "Кандидат биологических наук",
    "branch": "Биология",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат биологических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АР",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck20",
    "firstName": "Асият",
    "lastName": "Аджиева",
    "middleName": "Ибрагимовна",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck21",
    "firstName": "Аминат",
    "lastName": "Аджиева",
    "middleName": "Мухаджировна",
    "maidenName": "Айбазова",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck22",
    "firstName": "Зинхар",
    "lastName": "Аджиева",
    "middleName": "Исмаиловна",
    "maidenName": "Батчаева",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЗ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck23",
    "firstName": "Мадина",
    "lastName": "Аджиева",
    "middleName": "Манафовна",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck24",
    "firstName": "Фатима",
    "lastName": "Аджиева",
    "middleName": "Асхатовна",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АФ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck25",
    "firstName": "Эмма",
    "lastName": "Аджиева",
    "middleName": "Асланбековна",
    "maidenName": "",
    "degree": "Кандидат исторических наук",
    "branch": "История",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат исторических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АЭ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck26",
    "firstName": "Али",
    "lastName": "Айбазов",
    "middleName": "Хыйсаевич",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck27",
    "firstName": "Борис",
    "lastName": "Айбазов",
    "middleName": "Адейович",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АБ",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck28",
    "firstName": "Махар",
    "lastName": "Айбазов",
    "middleName": "Маратович",
    "maidenName": "",
    "degree": "Кандидат юридических наук",
    "branch": "Юриспруденция",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат юридических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АМ",
    "files": [],
    "notes": "уточнить",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck29",
    "firstName": "Айшат",
    "lastName": "Айбазова",
    "middleName": "Азретовна",
    "maidenName": "",
    "degree": "Кандидат экономических наук",
    "branch": "Экономика",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат экономических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  },
  {
    "id": "ck30",
    "firstName": "Асият",
    "lastName": "Айбазова",
    "middleName": "Кемаловна",
    "maidenName": "",
    "degree": "Кандидат педагогических наук",
    "branch": "Общественные науки",
    "birth": "",
    "education": "",
    "postgraduate": "",
    "titleInfo": "Кандидат педагогических наук.",
    "thesis": "",
    "work": "",
    "publications": [],
    "photoInitials": "АА",
    "files": [],
    "notes": "",
    "ethnicGroup": "qarachay",
    "sourceListDate": "28.09.2025"
  }
],
  files: [
    { id: 'f1', personId: 'd1', title: 'История письменной традиции', branch: 'Филология', year: 2021, type: 'Книга', url: '#' },
    { id: 'f2', personId: 'd1', title: 'Научный стиль и терминология', branch: 'Филология', year: 2023, type: 'Статья', url: '#' },
    { id: 'f3', personId: 'd2', title: 'Цифровые модели производственных линий', branch: 'Технические науки', year: 2022, type: 'Монография', url: '#' },
    { id: 'f4', personId: 'd3', title: 'Научные экосистемы регионов', branch: 'Экономика', year: 2024, type: 'Книга', url: '#' }
  ],
  news: [
    { id: 'n1', title: 'Запуск цифрового каталога проекта', date: '12.04.2026', text: 'Открыт единый каталог докторов и кандидатов наук с карточками, поиском, фильтрацией и библиотекой научных публикаций.' },
    { id: 'n2', title: 'Обновление раздела библиотеки', date: '04.04.2026', text: 'Для публикаций добавлены фильтры по автору, отрасли науки и году публикации, а также карточки файлов с быстрым доступом.' },
    { id: 'n3', title: 'Начат приём заявок на регистрацию', date: '28.03.2026', text: 'Регистрация новых участников проходит через форму и ручную модерацию администратора проекта.' }
  ],
  events: [
    { id: 'e1', title: 'Научная встреча по цифровым архивам', date: '15.05.2026', text: 'Обсуждение структуры научных архивов, каталогизации публикаций и цифрового доступа к материалам.' },
    { id: 'e2', title: 'Круглый стол по гуманитарным исследованиям', date: '29.05.2026', text: 'Экспертная дискуссия по вопросам языка, истории и культурного наследия.' },
    { id: 'e3', title: 'Семинар по научной коммуникации', date: '11.06.2026', text: 'Практическая встреча по публикационной активности, цифровым профилям и распространению исследований.' }
  ],
  contacts: {
    phone: '+7 (000) 000-00-00',
    email: 'info@taulualimle.ru',
    address: 'Нальчик, проектный офис «Таулу Алимле»'
  }
};
